import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { AlertCircle, CheckCircle, AlertTriangle, Download } from 'lucide-react';
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export default function ResultCard({ result, preview }) {

  const getRiskIcon = () => {
    switch (result.risk) {
      case 'High':
        return <AlertCircle className="h-5 w-5" />;
      case 'Medium':
        return <AlertTriangle className="h-5 w-5" />;
      case 'Low':
        return <CheckCircle className="h-5 w-5" />;
      default:
        return <CheckCircle className="h-5 w-5" />;
    }
  };

  const getRiskColor = () => {
    switch (result.risk) {
      case 'High':
        return 'bg-red-100 text-red-800 border-red-200';
      case 'Medium':
        return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'Low':
        return 'bg-green-100 text-green-800 border-green-200';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  const getBarColor = (label) => {
    if (label === 'No DR') return '#10b981';
    if (label === 'Mild') return '#f59e0b';
    if (label === 'Moderate') return '#f97316';
    if (label === 'Severe') return '#ef4444';
    return '#2C7BE5';
  };

  // ✅ REAL PDF DOWNLOAD
const handleDownloadReport = () => {
  const pdf = new jsPDF();

  // 🏥 HEADER
  pdf.setFontSize(20);
  pdf.setTextColor(44, 123, 229);
  pdf.text("RETScan AI", 20, 20);

  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text("Diabetic Retinopathy Detection Report", 20, 28);

  pdf.setLineWidth(0.5);
  pdf.line(20, 32, 190, 32);

  // 👤 PATIENT DETAILS
  pdf.setFontSize(12);
  pdf.text(`Patient Name: John Doe`, 20, 45);
  pdf.text(`Age: 45`, 20, 52);
  pdf.text(`Gender: Male`, 20, 59);
  pdf.text(`Date: ${new Date().toLocaleDateString()}`, 140, 45);

  // 🧠 DIAGNOSIS
  pdf.setFontSize(14);
  pdf.text("Diagnosis Summary", 20, 75);

  pdf.setFontSize(12);
  pdf.text(`Prediction: ${result.prediction}`, 20, 85);
  pdf.text(`Confidence: ${result.confidence.toFixed(2)}%`, 20, 92);
  pdf.text(`Risk Level: ${result.risk}`, 20, 99);

  // 📊 PROBABILITY TABLE
  pdf.setFontSize(14);
  pdf.text("Probability Breakdown", 20, 115);

  let y = 125;
  Object.entries(result.probabilities).forEach(([label, value]) => {
    pdf.setFontSize(12);
    pdf.text(`${label}`, 20, y);
    pdf.text(`${value.toFixed(2)}%`, 100, y);
    y += 8;
  });

  // 💊 RECOMMENDATION
  pdf.setFontSize(14);
  pdf.text("Medical Recommendation", 20, y + 10);

  pdf.setFontSize(12);
  const splitText = pdf.splitTextToSize(result.suggestion, 160);
  pdf.text(splitText, 20, y + 20);

  // ✍️ SIGNATURE
  pdf.line(140, 250, 190, 250);
  pdf.setFontSize(10);
  pdf.text("Doctor Signature", 145, 258);

  // 🏁 FOOTER
  pdf.setFontSize(10);
  pdf.text("Generated by RETScan AI System", 20, 280);

  pdf.save("RETScan_Medical_Report.pdf");
};
/*
const handleDownloadReport = async () => {
  console.log("Download clicked");

  const element = document.getElementById("report-section");

  if (!element) {
    alert("Report section not found!");
    return;
  }

  // 🔥 CLONE the element (VERY IMPORTANT FIX)
  const clone = element.cloneNode(true);

  // Apply safe styles
  clone.style.background = "#ffffff";
  clone.style.color = "#000000";
  clone.style.padding = "20px";

  // Remove problematic classes
  clone.querySelectorAll("*").forEach((el) => {
    el.style.backgroundColor = "#ffffff";
    el.style.color = "#000000";
    el.style.borderColor = "#cccccc";
  });

  document.body.appendChild(clone);

  try {
    const canvas = await html2canvas(clone, {
      backgroundColor: "#ffffff",
    });

    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF();
    const imgWidth = 190;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 10, 10, imgWidth, imgHeight);
    pdf.save("RETScan_Report.pdf");
  } catch (err) {
    console.error(err);
    alert("PDF generation failed");
  }

  // Clean up
  document.body.removeChild(clone);
};
*/
  return (
    <Card>
      {/* 👇 Wrap everything for PDF */}
      <div id="report-section">

        <CardHeader>
          <CardTitle>Diagnosis Result</CardTitle>
        </CardHeader>

        <CardContent className="space-y-6">

          {/* Prediction */}
          <div className="text-center p-6 bg-muted rounded-xl">
            <p className="text-sm text-muted-foreground mb-2">AI Prediction</p>
            <h2 className="text-2xl font-semibold">{result.prediction}</h2>
            <p className="text-sm text-muted-foreground mt-1">
              Confidence: {result.confidence.toFixed(2)}%
            </p>
          </div>

          {/* Risk Level */}
          <div>
            <p className="text-sm text-muted-foreground mb-2">Risk Level</p>
            <div className={`flex items-center gap-2 px-4 py-3 rounded-xl border-2 ${getRiskColor()}`}>
              {getRiskIcon()}
              <span className="font-medium">{result.risk} Risk</span>
            </div>
          </div>

          {/* Probabilities */}
          <div>
            <p className="text-sm text-muted-foreground mb-3">Probability Distribution</p>
            <div className="space-y-3">
              {Object.entries(result.probabilities).map(([label, value]) => (
                <div key={label}>
                  <div className="flex justify-between mb-1.5">
                    <span className="text-sm font-medium">{label}</span>
                    <span className="text-sm font-medium">{value.toFixed(2)}%</span>
                  </div>
                  <div className="w-full bg-muted rounded-full h-2.5 overflow-hidden">
                    <div
                      className="h-full rounded-full transition-all duration-500"
                      style={{
                        width: `${value*100}%`,
                        backgroundColor: getBarColor(label),
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Suggestion */}
          <div className="bg-blue-50 border-2 border-blue-200 rounded-xl p-4">
            <h4 className="font-medium text-blue-900 mb-2">Medical Recommendation</h4>
            <p className="text-sm text-blue-800">{result.suggestion}</p>
          </div>

        </CardContent>
      </div>

      {/* 👇 Button OUTSIDE so it won't appear in PDF */}
      <div className="p-4">
        <Button 
          onClick={handleDownloadReport} 
          className="w-full bg-[#2C7BE5] hover:bg-[#1e5bbf]"
        >
          <Download className="h-4 w-4 mr-2" />
          Download Report
        </Button>
      </div>

    </Card>
  );
}